name: gonitor_mobile
publish_to: 'none'
description: Gonitor Flutter mobile client for monitoring and task operations.
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
